# Generated by Django 5.0.2 on 2024-04-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GdsSystem', '0005_remove_projeto_conteudo_remove_projeto_periodos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='visualizacoes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
