# Generated by Django 5.0.2 on 2024-05-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GdsSystem', '0006_projeto_likes_projeto_visualizacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='desafio_para_casa',
            new_name='ambiente',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='distintivo',
            new_name='desejos',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='exercicio_em_equipe',
            new_name='envolvimento',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='falha',
            new_name='era',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='historia',
            new_name='fim',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='insignias',
            new_name='herois',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='item_secreto',
            new_name='hierarquias',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='mecanica',
            new_name='historia_jogador',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='perigo',
            new_name='historia_mundo',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='problema',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='problema_final',
            new_name='jornada',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='serie',
            new_name='mundo',
        ),
        migrations.AddField(
            model_name='projeto',
            name='novo_mundo',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='obstaculos',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='personagens_secundarios',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='plano_maligno',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='premio',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='problema_ambiente',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='problema_jogador',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='punicao',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='recompensa_jogo',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='reconhecimento',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='rotina',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='segredo',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='viloes',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='detalhe',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='emboscada',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='feridos',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
