# Generated by Django 5.0.2 on 2024-05-02 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GdsSystem', '0007_rename_desafio_para_casa_projeto_ambiente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='recompensa',
            new_name='recompensa_virtual',
        ),
    ]
