# Generated by Django 5.0.2 on 2024-05-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GdsSystem', '0009_perfil_bio_perfil_cidade_perfil_estado_perfil_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
