# Generated by Django 5.0.2 on 2024-06-02 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GdsSystem', '0011_remove_projeto_acontecimento_remove_projeto_ambiente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='likes',
        ),
        migrations.AddField(
            model_name='projeto',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='curtidas_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='visualizacoes',
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, default=None, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GdsSystem.projeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='comentarios',
            field=models.ManyToManyField(blank=True, related_name='comentarios_set', through='GdsSystem.Comentario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projeto',
            name='visualizacoes',
            field=models.ManyToManyField(blank=True, related_name='visualizacoes_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
